import 'package:flutter/material.dart';

class AppProvider extends InheritedWidget {
  final String lang;
  final ThemeMode themeMode;
  final VoidCallback onToggleLang;
  final VoidCallback onToggleTheme;

  const AppProvider({
    super.key,
    required this.lang,
    required this.themeMode,
    required this.onToggleLang,
    required this.onToggleTheme,
    required super.child,
  });

  static AppProvider of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<AppProvider>()!;
  }

  bool get isAr => lang == 'ar';
  bool get isDark => themeMode == ThemeMode.dark;

  String t(String key) {
    return (isAr ? _ar[key] : _en[key]) ?? _en[key] ?? key;
  }

  @override
  bool updateShouldNotify(AppProvider old) => 
      old.lang != lang || old.themeMode != themeMode;

  static const _en = {
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.welcome': 'Welcome Back',
    'auth.slogan': 'Your future starts here. Integrated dashboard for efficient management.',
    'auth.subtitle': 'Enter your credentials to access your dashboard',
    'auth.forgot_password': 'Forgot password?',
    'auth.login_btn': 'Sign In',
    'auth.footer': '© 2026 VIVUM Tech. All rights reserved.',
    'auth.err.empty': 'Please enter email and password',
    'auth.err.invalid': 'Invalid email or password',
    'auth.err.wrong_pass': 'Wrong password',
    'auth.err.disabled': 'This account has been disabled',
    'auth.err.invalid_email': 'Invalid email address',
    'auth.err.too_many': 'Too many attempts. Please try later',
    'auth.err.inactive': 'This account is currently inactive. Please contact administration.',
    'auth.err.unknown': 'An unexpected error occurred during login',
    'dash.overview': 'Overview',
    'dash.projects': 'Projects',
    'dash.messages': 'Messages',
    'dash.testimonials': 'Testimonials',
    'dash.logout': 'Logout',
    'dash.logout_confirm': 'Are you sure you want to log out of the system?',
    'dash.logout_btn': 'Log Out',
    'dash.cancel_btn': 'Cancel',
    'dash.users': 'User Management',
    'dash.total_projects': 'Total Projects',
    'dash.total_messages': 'Total Messages',
    'dash.total_testimonials': 'Total Testimonials',
    'dash.total_users': 'Total Users',
    'dash.welcome': 'Welcome back,',
    'dash.quick_actions': 'Quick Actions',
    'dash.recent_activity': 'Recent Activity',
    'dash.add_project_btn': 'New Project',
    'dash.view_messages_btn': 'Messages',
    'user.add': 'Add User',
    'user.edit': 'Edit User',
    'user.name': 'Name',
    'user.email': 'Email',
    'user.phone': 'Phone (Optional)',
    'user.role': 'Role',
    'user.admin': 'Admin',
    'user.messaging': 'Messaging',
    'user.password': 'Password',
    'user.confirm_password': 'Confirm Password',
    'user.active': 'Active',
    'user.inactive': 'Inactive',
    'user.status': 'Status',
    'user.actions': 'Actions',
    'user.delete': 'Delete',
    'user.save': 'Save',
    'user.cancel': 'Cancel',
    'user.reset_pass': 'Send Reset Email',
    'user.val.name': 'Please enter name',
    'user.val.email': 'Please enter email',
    'user.val.pass_short': 'Must be 4 characters or more',
    'user.val.pass_match': 'Passwords do not match',
    'user.delete_confirm': 'Are you sure you want to delete this user?',
    'user.reset_confirm': 'Send password reset email to this user?',
    'user.reset_sent': 'Reset email sent successfully',
    'user.enter_email_reset': 'Enter email to receive reset link',
    'proj.add': 'Add Project',
    'proj.edit': 'Edit Project',
    'proj.title': 'Title',
    'proj.id': 'Project ID',
    'proj.category': 'Category',
    'proj.industry': 'Industry',
    'proj.location': 'Location',
    'proj.year': 'Year',
    'proj.challenge': 'The Challenge',
    'proj.solution': 'The Solution',
    'proj.result': 'The Result',
    'proj.tech': 'Technologies (Comma separated)',
    'proj.accent_color': 'Accent Color (Int)',
    'proj.colors': 'Primary Colors (Int, Comma separated)',
    'proj.images': 'Project Images',
    'proj.uploading': 'Uploading images to Supabase...',
    'msg.from': 'From',
    'msg.date': 'Date',
    'msg.unread': 'Unread',
    'msg.read': 'Read',
    'msg.replied': 'Replied',
    'msg.mark_read': 'Mark as Read',
    'msg.mark_replied': 'Mark as Replied',
    'msg.copy_email': 'Copy Email',
    'msg.copy_phone': 'Copy Phone',
    'msg.filter_all': 'All Messages',
    'msg.filter_unread': 'Unread Only',
    'msg.filter_replied': 'Replied Only',
  };

  static const _ar = {
    'auth.login': 'تسجيل الدخول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.welcome': 'مرحباً بك مجدداً',
    'auth.slogan': 'مستقبلك يبدأ هنا. لوحة تحكم متكاملة لإدارة أعمالك بكفاءة وذكاء.',
    'auth.subtitle': 'أدخل بياناتك للوصول إلى لوحة التحكم الخاصة بك',
    'auth.forgot_password': 'نسيت كلمة المرور؟',
    'auth.login_btn': 'دخول النظام',
    'auth.footer': '© 2026 VIVUM Tech. جميع الحقوق محفوظة.',
    'auth.err.empty': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
    'auth.err.invalid': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'auth.err.wrong_pass': 'كلمة المرور غير صحيحة',
    'auth.err.disabled': 'هذا الحساب تم تعطيله',
    'auth.err.invalid_email': 'عنوان البريد الإلكتروني غير صحيح',
    'auth.err.too_many': 'محاولات كثيرة خاطئة. يرجى المحاولة لاحقاً',
    'auth.err.inactive': 'هذا الحساب غير مفعل حالياً. يرجى مراجعة الإدارة.',
    'auth.err.unknown': 'حدث خطأ أثناء تسجيل الدخول',
    'dash.overview': 'نظرة عامة',
    'dash.projects': 'المشاريع',
    'dash.messages': 'الرسائل',
    'dash.testimonials': 'آراء العملاء',
    'dash.logout': 'تسجيل الخروج',
    'dash.logout_confirm': 'هل أنت متأكد من رغبتك في تسجيل الخروج من النظام؟',
    'dash.logout_btn': 'خروج',
    'dash.cancel_btn': 'إلغاء',
    'dash.users': 'إدارة المستخدمين',
    'dash.total_projects': 'إجمالي المشاريع',
    'dash.total_messages': 'إجمالي الرسائل',
    'dash.total_testimonials': 'إجمالي الآراء',
    'dash.total_users': 'إجمالي المستخدمين',
    'dash.welcome': 'مرحباً بك مجدداً،',
    'dash.quick_actions': 'إجراءات سريعة',
    'dash.recent_activity': 'آخر النشاطات',
    'dash.add_project_btn': 'مشروع جديد',
    'dash.view_messages_btn': 'الرسائل',
    'user.add': 'إضافة مستخدم',
    'user.edit': 'تعديل مستخدم',
    'user.name': 'الاسم',
    'user.email': 'البريد الإلكتروني',
    'user.phone': 'رقم الهاتف (اختياري)',
    'user.role': 'الصلاحية',
    'user.admin': 'أدمن',
    'user.messaging': 'استقبال رسائل',
    'user.password': 'كلمة السر',
    'user.confirm_password': 'تأكيد كلمة السر',
    'user.active': 'مفعل',
    'user.inactive': 'غير مفعل',
    'user.status': 'الحالة',
    'user.actions': 'العمليات',
    'user.delete': 'حذف',
    'user.save': 'حفظ',
    'user.cancel': 'إلغاء',
    'user.reset_pass': 'إرسال بريد إعادة تعيين',
    'user.val.name': 'يرجى إدخال الاسم',
    'user.val.email': 'يرجى إدخال البريد',
    'user.val.pass_short': 'يجب أن تكون 4 محارف أو أكثر',
    'user.val.pass_match': 'كلمات السر غير متطابقة',
    'user.delete_confirm': 'هل أنت متأكد من حذف هذا المستخدم؟',
    'user.reset_confirm': 'هل تريد إرسال رابط إعادة تعيين كلمة السر لهذا المستخدم؟',
    'user.reset_sent': 'تم إرسال بريد إعادة التعيين بنجاح',
    'user.enter_email_reset': 'أدخل البريد الإلكتروني لاستلام رابط الإعادة',
    'proj.add': 'إضافة مشروع',
    'proj.edit': 'تعديل مشروع',
    'proj.title': 'عنوان المشروع',
    'proj.id': 'معرف المشروع (ID)',
    'proj.category': 'التصنيف',
    'proj.industry': 'المجال (Industry)',
    'proj.location': 'الموقع (Location)',
    'proj.year': 'السنة',
    'proj.challenge': 'التحدي',
    'proj.solution': 'الحل',
    'proj.result': 'النتيجة',
    'proj.tech': 'التقنيات (افصل بينها بفاصلة)',
    'proj.accent_color': 'لون التمييز (Accent Color Int)',
    'proj.colors': 'الألوان الأساسية (Ints مفصولة بفاصلة)',
    'proj.images': 'صور المشروع',
    'proj.uploading': 'جاري رفع الصور إلى سوبابيز...',
    'msg.from': 'من',
    'msg.date': 'التاريخ',
    'msg.unread': 'غير مقروء',
    'msg.read': 'مقروء',
    'msg.replied': 'تم الرد',
    'msg.mark_read': 'تحديد كمقروء',
    'msg.mark_replied': 'تحديد كتم الرد',
    'msg.copy_email': 'نسخ الإيميل',
    'msg.copy_phone': 'نسخ الهاتف',
    'msg.filter_all': 'كل الرسائل',
    'msg.filter_unread': 'غير المقروءة',
    'msg.filter_replied': 'تم الرد عليها',
  };
}
